input {
  tcp {
    port => 5000
    codec => json_lines
    type => "spring-boot"
  }
}

filter {
  if [type] == "spring-boot" {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "endorsement-service" }
    }

    date {
      match => [ "@timestamp", "ISO8601" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "endorsement-logs-%{+YYYY.MM.dd}"
  }
}
