gatling {
  core {
    encoding = "utf-8"
    simulationClass = ""
  }
  http {
    fetchedCssCacheMaxCapacity = 100
    fetchedHtmlCacheMaxCapacity = 100
    perUserCacheMaxCapacity = 100
    warmUpUrl = ""
    pooledConnectionIdleTimeout = 60000
    requestTimeout = 60000
    enableHostnameVerification = false
    dns {
      queryTimeout = 5000
      maxQueriesPerResolve = 6
    }
  }
  data {
    writers = [console, file]
    console {
      light = false
      writePeriod = 5
    }
    file {
      bufferSize = 8192
    }
    graphite {
      light = false
      host = "localhost"
      port = 2003
      protocol = "tcp"
      rootPathPrefix = "gatling"
      bufferSize = 8192
      writePeriod = 1
    }
  }
  charting {
    noReports = false
    maxPlotPerSeries = 1000
    indicators {
      lowerBound = 200
      higherBound = 500
    }
  }
}
